### ISSUE TITLE
Please update "Important Links"

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#11]
@conlaccento - could you please update the Open Gov platform's "Important Links" on the left-hand side of the submission form to go to the relevant Open Gov pages? For the Download link, I will need to send you a .doc file by the end of the week.

**Comment by conlaccento** [comment]
Done, I'll wait for the file to complete the task

**Comment by jlberryhill** [comment]
Perfect -- thanks, @conlaccento
