### ISSUE TITLE
A few back-end admin adjustments needed

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#12]
@conlaccento -- on the back-end, I'm hoping you can make a few adjustments for Open Gov Admins. 

I am logged into an Open Gov Admin account (called OpenGovAdmin). 

On the navigation bar to the left, under "Case Studies", Open Gov admins are able to access a numbe rof things (screenshot below).

![navbar](https://user-images.githubusercontent.com/7728105/48123694-d90a0480-e27a-11e8-9d21-06065993b3bd.PNG)

Could you please adjust this so they can access only the following:

- All Case Studies

- Add a Case Study

- Innovation Tags OpenGov (does not appear at all right now)

- Innovation Badges OpenGov

This would mean _removing_ their ability to access:

- Case type

- Countries

- Innovation Tags (opsi)

- Innovation Badges (opsi)

**Comment by conlaccento** [comment]
Done
