### ISSUE TITLE
A couple back-end editing issues

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#14]
@conlaccento -

I don't think the name/org/email fields are auto-completing in the back end. Could you please have these fields auto-populate? Also, for the Open Gov form, the question on "Are you a Public Sector employee..." is not relevant for the Open Gov form. Could you please sliminate this question (and also the sub-questions for if they choose No) for the Open Gov back-end? These questions are already fone from the front-end submission form. 

![prefill](https://user-images.githubusercontent.com/7728105/48126074-8fbcb380-e280-11e8-9b3e-654ef9d88fe0.PNG)

**Comment by conlaccento** [comment]
Hi @jlberryhill. Autopopulate works only in frontend for email field: this is how it works before our intervention. This make sense considering that we plan to optimize the front end form submission experience, and also an admin can use the frontend form for submission.

About the public-sector employee field we now make it appears only if the case type is OPSI.

**Comment by jlberryhill** [comment]
Thanks, @conlaccento, but I'm not sure I understand. I just submitted a test case using the open gov form. When I check it in the back-end, the email address is not auto-populated. 

The email, Your Name, and Your Organisations fields already auto-populate on the OPSI form, but they do not on the Open Gov form.

**Comment by conlaccento** [comment]
Hi @jlberryhill, I checked again the issue and this remember me that we hide those fields (name, email and organisation) in OpenGov form: form this reason the function that autopopulate them can't run.

Hi we want to autopopulate them we need to show them: can I proceed?

**Comment by jlberryhill** [comment]
Sorry @conlaccento but I dont really think this is accurate. I think you are perhaps mixing up thinking about two sets of questions. There is nowhere on the OPSI form where is asks for the submitting user's name or email address. If they are not a government official, it does ask for _someone else's_ name and email address if they have it, but it is not required. The fields we got rid of for the Open Gov form were the details about _someone else_, because the Open Gov team doesn't care if they have a government contact.

Having these fields auto-populate is important and I think there must be a way for it to happen since it was already happening with the OPSI cases.

**Comment by jlberryhill** [comment]
@conlaccento - just as one addition to my previous comment -- these items are derived from the user's profile, which is why I think they can be pre-populated on the back-end.

**Comment by conlaccento** [comment]
@jlberryhill thanks for your clarification, now the fields should populate automatically
