### ISSUE TITLE
Minor text changes to Open Gov submission form

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#16]
@conlaccento  -- could you please make the minor text updates from the attached file to the Open Gov submission form?

[text edits to OG form.docx](https://github.com/oecd-opsi/opsi/files/2557258/text.edits.to.OG.form.docx)

**Comment by jlberryhill** [comment]
A few more minor text changes:

![textchanges](https://user-images.githubusercontent.com/7728105/48137353-25b50600-e2a2-11e8-9509-0880af2b3b1c.PNG)

**Comment by conlaccento** [comment]
Done
