### ISSUE TITLE
Link to word .doc version of form

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#18]
Hi @conlaccento -- Could you please make the following two changes to the Open Gov submission form?

- Please add a new link to "Download the full list of submission questions", linking to the URL below. This would mirror the way it is done on the OPSI submission form (screenshot below).
![links](https://user-images.githubusercontent.com/7728105/48260400-a3505180-e41b-11e8-98ac-b1996d2bf021.PNG)

- For the navigation bar links to the bottom-left, Please change the URL for "Download submission questions list" to the URL below

 
https://oecd-opsi.org/wp-content/uploads/2018/11/Open-Government-Case-Study-Submission-Form.doc

**Comment by conlaccento** [comment]
Done
