### ISSUE TITLE
Change titles for Open Gov and OPSI aggregate pages

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#19]
Hi @conlaccento -- I think we're just about there. Thanks for your hard work on this!

Small change. Could you please change the <title> for 
https://oecd-opsi.org/case_type/opsi/ and
https://oecd-opsi.org/case_type/open-government/

Right now it says "OPSI Archives" and "Open Government Archives". Could  you please change it to "OPSI Innovations" and "Open Government Innovations" instead?

**Comment by conlaccento** [comment]
You're welcome.

Titles changed.
