### ISSUE TITLE
Feedback on Case Study Aggregate listing

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#2]
Hi all ,

Thanks for your work on developing the aggregate case study page! I am pasting your feedback below, and will respond to it with our feedback.
----------------------
Good morning everyone,

while working on the GitHub issues related to Deliverable 1, we completed Deliverable 2

The URL for the Open Gov aggregate list is the following:
https://staging.oecd-opsi.org/case_type/open-government/

The URL for OECD aggregate list will become:
https://staging.oecd-opsi.org/case_type/oecd/

At the same time, the original URL https://staging.oecd-opsi.org/innovations/ from now on will show the full list of all case studies.
Would you like to implement a redirect?

Feel free to test Deliverable 2 and let us have your feedback and comments.

**Comment by jlberryhill** [comment]
Hi @conlaccento -- please see below for the Open Gov tags. They will have a few more to add in the near future, but this is a good foundation.

implementation
enablers
transparency
integrity
accountability
participation
strategy
open state
open parliament
open local government
engagement
co-creation
laws
regulations
skills
resources
co-ordination
forum
monitoring
evaluation
impact
communication
media
open data
digital government
stakeholders
diversity
youth
gender
openstate
SDG
water
health
social policy
natural resources
infrastructure
open contracting
anti-corruption

**Comment by conlaccento** [comment]
Hello, I will reply point by point below.
> 
> 
> For the URLs, do you mean that the OPSI innovaion case studies would be at https://staging.oecd-opsi.org/case_type/oecd/ and the Open Gov team case studies would be at https://staging.oecd-opsi.org/case_type/oecd/? If so, would it be possible to change the one URL from https://staging.oecd-opsi.org/case_type/oecd/ to https://staging.oecd-opsi.org/case_type/opsi/? This is because the OECD is the umbrealla organisation for both teams.
> 
> For the https://staging.oecd-opsi.org/innovations/ URL, could you please redirect this to the OPSI case studies only?
Done
> 
> Case study counts:
> 
>     * It seems like the counts are a bit off. The OPSI case study count appears to be correct (total cases = 15, total shown = 15). However, the Open Gov count appears to be off. There is only one case, but it says total cases = 15 (see screenshot below).
>       ![image](https://user-images.githubusercontent.com/7728105/47211547-065b4500-d396-11e8-87a0-b95f60823953.png)
> 
Fixed
> 
> Comments specific to open gov:
> 
>     * Just a flag - in my comments for Deliverable 1 yesterday, I mentioned that the Open Gov team does not need the Stage of Innovation questions. Since this will go away, the Open Gov aggregate page will not need to be filterable by this.
Done
> 
>     * Form the comments yesterday, the filtering also changes a bit for "Level of Government".  On the Open Gov form, there is now an "Organisation Type" field. Is it possible to add, above the "Level of Government" filtering option a new filtering option for "Organisation Type"? Would it then be possible for the "Level of Government" filtering option to only appear if the user selects "Government" for "Organisation Type". If this is no possible, please eliminate the "Level of Government" filtering option.
Done
> 
>     * Similar the comment before this one, on the individual page for each case study, could you please add a "Organisation Type" indicator above "Level of government", and only have "Level of government" appear if the organisation type = government?
Done
> 
>     * I still need to get you a full set of the Open Gov tags, as they will be different.
> 
>     * For this and all of the Open Gov components, the tags are below. They have a handful more to add, but it would be good to start with these for now.
We're working to properly filter the tags for the two case typology (OPSI and OpenGov)
> 
>     * One more flag -- Since all of the Open Gov cases and OPSI cases are the same post type, I am wondering if this will make it impossible to have subtle difference in how the cases are represented on the front-end individual pages. For example, I suggested some changes to the submission form yesterday, related to merging two sections since there was only one question on one of the pages. Is it possible to have the Open Gov cases reflect this merged section on the front-end, while the OPSI cases still have it broken out in two sections?
The fields group structure makes it difficult to move fields from one group (section) to another.
Furthermore trying to achieve this in front end means to loose the flexibility and maintainability level of the system, leading to difficulty for future improvement. We suggest not to break the actual fields group management for both back and front end.

**Comment by jlberryhill** [comment]
Hi @conlaccento -- thanks for incorporating my feedback. A few more items below:

- On the OPSI platform, when I'm on the aggregate page, clicking on a country flag does not take me to a filtered vie that shows only cases for that country. Instead, it takes me to the full list of case studies. When I'm on the Open Gov page, when i click a flag, it takes me to the OPSI case study platform. 

- I  just notice you are still working on  differentiating the tag sets. Please let me know when that is ready, as its a really important component. 

I will look through the individual pages and the back-end and provide feedback on those items tomorrow.

**Comment by conlaccento** [comment]
Hi again @jlberryhill =)

The flag issue is solved.
