### ISSUE TITLE
Badges on individual page not linking to filtered view of all cases

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#23]
Hi @conlaccento -- minor issues. 

When I'm on an individual case study page, when I click on the icon for a specific badge, it doe snot take me to a filtered view of all of the case studies (i.e., does now show me all of the case studies that have the same badge). Could you please make it so this occurs?

![badges](https://user-images.githubusercontent.com/7728105/48485114-463c0d80-e818-11e8-802c-fbc564fddc31.PNG)

**Comment by conlaccento** [comment]
Hi @jlberryhill, now the link should work properly
