### ISSUE TITLE
Some sidebar items are duplicated

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#25]
Hi @conlaccento -- fairly minor issue below. 

![sidebar](https://user-images.githubusercontent.com/7728105/48673341-8fee6600-eb40-11e8-97fc-552f8ae051ef.png)

**Comment by jlberryhill** [comment]
on the right hand side when you’re in some pages, there’s some double ups in the right hand bit – e.g. two of the OPSI on Twitter and two of Recent Comments.

**Comment by conlaccento** [comment]
Solved
