### ISSUE TITLE
Error when approving/deleting new users

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#26]
@conlaccento 

Would you mind checking the error below? We keep receiving it when deleting or approving new users.  Thanks!

![mailerror](https://user-images.githubusercontent.com/7728105/51178797-018a2c80-18c4-11e9-8746-5fc8b606cf20.png)

**Comment by conlaccento** [comment]
Hello @jlberryhill, we will check it as soon as possible

**Comment by conlaccento** [comment]
Hi @jlberryhill, I try to check the issue but everything worked as expected.
Can you give us more details to replicate the error.
However I do not think it is an error due to our intervention, we didn't work on users management.

**Comment by jlberryhill** [comment]
Hi @conlaccento -- we are still having the same issue. It tends to happen when we try to delete a bunch of accounts at the same time which we have needed to do because we had a ton of spam-bot registrations. You can try to replicate the error yourself by searching for Pending users with email addresses ending in ".ru" (type that into the search box and click all the pending users and try to delete. It may not occur the first time, so try again.  We have a new purchase order in place for bux fixes that arent related to Black Studio development (cc @marcochiesi)

**Comment by conlaccento** [comment]
Hello @jlberryhill, now bulk delete works and I deleted all .ru users.
Let me know if you noticed further problems.

**Comment by conlaccento** [comment]
Hi @jlberryhill, the problem is with Google API: when you delete an user the system send an email notification to this user. 
When you try to bulk delete fake account, Google try to send all this email to fake addresses, and reply with an error that stops the deleting process.
Now we disabled the notifications on user delete so the problem will no longer show up.

**Comment by jlberryhill** [comment]
Thanks @conlaccento. We gave it a try and unfortunately it seems to still be happening.

**Comment by conlaccento** [comment]
@jlberryhill can you tell me if there are other spam accounts that I can delete for testing?

**Comment by conlaccento** [comment]
@jlberryhill we probably found the solution, can you test again and give me a feedback? Thanks

**Comment by jlberryhill** [comment]
Hi @conlaccento  -- It's working - thanks!
