### ISSUE TITLE
BuddyPress emails not sending

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#27]
@conlaccento @fabio-bs @conlaccento -- For the OPSI site, emails for BuddyPress don't seem to be sending. At least not the ones for receiving a private message. The email setting are  at https://oecd-opsi.org/wp-admin/edit.php?post_type=bp-email. Could you please take a look?

**Comment by jlberryhill** [comment]
As a flag -- all of our emails go through gmail api because AWS doesnt have a built-in mail server. Some other emails are working, though (e.g., new member signup)

**Comment by jlberryhill** [comment]
Hi @conlaccento -- just wanted to follow up on this to make sure you've seen it. Thanks!

**Comment by conlaccento** [comment]
Hello @jlberryhill, we are trying to find a solution and will update you soon

**Comment by fabio-bs** [comment]
Hi @jlberryhill , apparently BuddyPress by default uses its own function to send emails and therefore bypasses Gmail's SMTP settings. To solve I forced the use of the native WordPress function and now it works correctly. Can you please check and let me know if it works for you too?

**Comment by fabio-bs** [comment]
Hi @jlberryhill, I was wondering if you had the chance to verify everything was ok

**Comment by jlberryhill** [comment]
Hi @fabio-bs -- things seem to be working well. Thanks! Sorry for the delay - I was out of the office all last week.
