### ISSUE TITLE
Add new Organisation Type

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#28]
Hi @conlaccento -- For the open Gov case study platform (submission form and front-end),  could you please add a new Organisation Type for  "Independent Organisation"? This would be in addition to Government, NGO, Academia...

We can invoice this against the bug fix purchase order.  Thanks!!

**Comment by conlaccento** [comment]
Hi @jlberryhill, new option for Organisation type added

**Comment by jlberryhill** [comment]
Hi @conkaccento -- apologies, but could you please rename this to "Independent institution" (request of the Open Gov team). Thanks!

**Comment by jlberryhill** [comment]
@conlaccento -- mistyped your handle above.

**Comment by conlaccento** [comment]
Hi @jlberryhill, option renamed

**Comment by jlberryhill** [comment]
Thanks, @conlaccento!
