### ISSUE TITLE
Linking to case studies from Toolkit Navigator

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/opsi#30]
On the Toolkit Navigator, there are guide pages for each of the innovation disciplines, such as “Design” https://oecd-opsi.org/guide/design/
On the right, there is a box, (See how other governments are doing this work: Go to case studies)

Originally, the case study library had no cases, so it was boring to link to a filtered view for cases involving “Design.” However, now that there are cases, I want to now link to cases filtered by the discipline. 

I would like to connect all Guide pages in the Toolkit Navigator to related cases within that discipline. Below I included links to each guide page as well as links to filtered views in the case study platform. 
 https://oecd-opsi.org/guide/social-innovation/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=social-innovation

https://oecd-opsi.org/guide/public-policy/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=public-policy

https://oecd-opsi.org/guide/service-design/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=service-design

https://oecd-opsi.org/guide/digital-transformation/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=digital-and-tech

https://oecd-opsi.org/guide/strategic-design/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=strategic-design

https://oecd-opsi.org/guide/organisational-design/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=organisational-design

https://oecd-opsi.org/guide/behavioural-insights/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=behavioural-insights

https://oecd-opsi.org/guide/systems-change/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=systems-change

https://oecd-opsi.org/guide/international-development/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=international-development

https://oecd-opsi.org/guide/facilitation-and-codesign/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=process-facilitation-and-codesign

https://oecd-opsi.org/guide/product-design/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=product-design

https://oecd-opsi.org/guide/futures-and-foresight/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=futures-and-foresight

https://oecd-opsi.org/guide/open-government/
https://oecd-opsi.org/case_type/opsi/?_innovation_tags=open-government

**Comment by jlberryhill** [comment]
@innovativeangela --I think this might be something we can do on our own, Lets walk through it when you are back in the office.

**Comment by fabio-bs** [comment]
Hello everyone, the "Go to case studies" link is managed via code, so it is preferable that we make the change.
Changing the destination URL does not take much time and if you agree, I will proceed with the implementation.

**Comment by innovativeangela** [comment]
@fabio-bs if you are ok with making these quick changes, please do go ahead. It is faster and less riskier that way :)  All the destination URLs are above.

**Comment by fabio-bs** [comment]
@innovativeangela I have updated the "Case studies" links as you requested. The links are generated dynamically starting from the "Innovation Tag" field that I added to the individual guides (see attached image)
![case-studies-innovation-tags](https://user-images.githubusercontent.com/9032846/53007794-401d8480-3438-11e9-865a-ccd9a2a1de4c.jpg)

**Comment by innovativeangela** [comment]
Thank you!
