### ISSUE TITLE
Registration form allowing submissions without required fields completed

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#32]
Hi @conlaccento -- Not urgent, but the registration form is allowing users to submit requests to join without completing all of the required fields. This makes it difficult for us to screen registrants for approval/denial. As a result, we've had some spammer slip through. Could you please fix this?

**Comment by conlaccento** [comment]
Hi @jlberryhill, I just tested the registration form and everything works well, required fields were mandatory and all infos were registered in backend. Can you give me more information about this issue?

**Comment by conlaccento** [comment]
Hello @jlberryhill , have you had the opportunity to test again this issue?
