### ISSUE TITLE
Edit welcome email 

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#33]
The current email subject is "[Observatory of Public Sector Innovation] Activate your account"

The current email text is "To complete the activation of your account, go to the following link:" with a link after.

We would like to change the subject to "[Observatory of Public Sector Innovation] Registration request under review" 

And the email text to "A member of the OECD team will review your request for membership. You will receive an email once your account is approved. In the meantime, you may already submit a case study here. If your case pertains specifically to Open Government initiatives, please use the specialised submission for here."

In the above, the first "here" should link to https://oecd-opsi.org/case-study-form/ and the second "here" should link to https://oecd-opsi.org/case-study-form-open-government/.

**Comment by fabio-bs** [comment]
Hi @jlberryhill,
I have made the requested changes to the welcome email, can you please check it and let me know if everything is ok?

**Comment by fabio-bs** [comment]
Hi @jlberryhill, I was wondering if you had the chance to verify everything was ok
