### ISSUE TITLE
Permissions issues for non-logged-in users

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#5]
Hi @conlaccento -- there seem to be a few permissions issues for users who are no logged in.

- I can navigate to https://oecd-opsi.org/blog/; however, when I try to click on a specific blog entry, it takes me to a login page. 

- Same thing with Projects pages, which appear in aggregate at https://oecd-opsi.org/projects/. 

- I think there used to be additional menu items under "Our Work", such as "Projects" and "Publications".  These do not show up (see screenshot).
![capture16](https://user-images.githubusercontent.com/7728105/48071032-8af0f480-e1d9-11e8-9ba7-532f0d0ad984.PNG)

- Like the comment above, there should be a sub-menu with items under "About OPSI", but this does not appear.

**Comment by jlberryhill** [comment]
One more thing -- I just noticed that users who are not logged in are able to access https://oecd-opsi.org/case-study-form-open-government/. Only logged-in users (any permissions group, including Pending) should be able to access the submission form.

**Comment by conlaccento** [comment]
> 
> 
> Hi @conlaccento -- there seem to be a few permissions issues for users who are no logged in.
> 
>     * I can navigate to https://oecd-opsi.org/blog/; however, when I try to click on a specific blog entry, it takes me to a login page.
> 
>     * Same thing with Projects pages, which appear in aggregate at https://oecd-opsi.org/projects/.
> 
>     * I think there used to be additional menu items under "Our Work", such as "Projects" and "Publications".  These do not show up (see screenshot).
>       ![capture16](https://user-images.githubusercontent.com/7728105/48071032-8af0f480-e1d9-11e8-9ba7-532f0d0ad984.PNG)
> 
>     * Like the comment above, there should be a sub-menu with items under "About OPSI", but this does not appear.

Now everything should be displayed as expected

**Comment by conlaccento** [comment]
OpenGov form restricted for not logged users

**Comment by conlaccento** [comment]
@jlberryhill what about the restriction on the Opsi form page? Reachable by everyone or only for logged in users?

**Comment by jlberryhill** [comment]
@conlaccento -- I think this looks good now. Both OPSI form and Open Gov should be accessible by any logged-in user (ant nod accessible to users who are not logged in). This is how I think it works now.
