### ISSUE TITLE
Extra field on OPSI case study form

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#6]
@conlaccento -- there is an extra field on the OPSI case study platform under Tags (please see screenshot below). 

![extrafield](https://user-images.githubusercontent.com/7728105/48072000-e45a2300-e1db-11e8-95f7-81e327200116.PNG)

**Comment by conlaccento** [comment]
@jlberryhill I don't see this _ghost field_, could you delete browser cache and then try again?

**Comment by jlberryhill** [comment]
@conlaccento -- hmm. I cleared my cache and refreshed. Just to be clear, I'm on the live site on the OPSI case study platform. I just had a colleague try it, who is seeing the same field.

**Comment by conlaccento** [comment]
Sorry, I was checking the wrong form: issue fixed now.
