### ISSUE TITLE
Case preview links in Innovations tab in user profile go to 404

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#8]
@conlaccento -- I submitted two test case studies (one from each platform). The links that should go to platform-specific previews of the submitted case studies go to 404 errors. 

![404](https://user-images.githubusercontent.com/7728105/48078747-50438800-e1ea-11e8-9e5e-8b636a1cc04c.PNG)

The editing feature is opening cases in the correct submission form, which is great. thanks for fixing that.

**Comment by jlberryhill** [comment]
Hi @conlaccento -- they way is used to work is that a user could click on this link to view a previous of what their case study would look like once it is published (even if the case study is not yet published). This would allow auser to see what the final output would look like in order to determine whether they may want to make edits. So even though it is not fully published, the preview is still accessible to the user who submitted it.

**Comment by conlaccento** [comment]
Now it should work, can you confirm it?

**Comment by conlaccento** [comment]
Fixed now

**Comment by jlberryhill** [comment]
Thanks, @conlaccento. This does seem to be working well for some cases, and for some others i get 404.  Screenshots below. The only difference I can think of is that I am logged into an Open Gov Admin account for the one that is working, and a regular logged-in (non-admin) account for the one that results in a 404 error. In general, admins should be able to see all cases, and every submitting user should be able to see previers of _their_ cases. 

Working for:
![working](https://user-images.githubusercontent.com/7728105/48209276-01762980-e375-11e8-8e42-75b90106fc42.PNG)


404 for: 
![404b](https://user-images.githubusercontent.com/7728105/48209203-ddb2e380-e374-11e8-82c9-98877bbee981.PNG)

**Comment by conlaccento** [comment]
Hi @jlberryhill, now the previews should work as expected: all visible to opengov admin and previews visible to case owner. Can you confirm it?

**Comment by jlberryhill** [comment]
Hi @conlaccento -- It stil doesn't seem to be working for non-admin users. 

Below is a screenshot for cases I previously submitted with the account "CaseTest"
![404v3](https://user-images.githubusercontent.com/7728105/48262978-cd5a4180-e424-11e8-8a15-b0694fb0ecb3.PNG)

It works well when I use the account OpenGovAdmin though.

**Comment by conlaccento** [comment]
Now everything should work
