### ISSUE TITLE
Open Gov platform aggregate page should filter by open gov tags

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#9]
@conlaccento -  I cross-posted an OPSI case as an Open Gov case (so it shows up in both). When I view https://oecd-opsi.org/case_type/open-government/, the tags I can filter by are the OPSI tags. They should be the Open Gov tags when looking at https://oecd-opsi.org/case_type/open-government/, and the OPSI tags when looking at https://oecd-opsi.org/case_type/opsi. 

Screenshot below.

![tagfiltering](https://user-images.githubusercontent.com/7728105/48081414-47ee4b80-e1f0-11e8-9639-6f4507b2af1a.PNG)

**Comment by conlaccento** [comment]
Solved, thank you

**Comment by jlberryhill** [comment]
Hi @conlaccento -- this issue appears the same for me. I am at https://oecd-opsi.org/case_type/open-government/. When click on the drop-down box under "Innovation Tags", it shows me the OPSI tags. It should show me the Open Gov tags instead. I don't think that the Open Gov team has gone into the individual cases that are liste don this page yet to add their own set of tags, so for now I think the Innovation Tags filter options would be blank until they add their tags to each individual case. 

Similarly, even though I am on the Open Gov page with their case studies listed (https://oecd-opsi.org/case_type/open-government/), the OPSI tags are what appear alongside each individual case study (see screenshot below). When on the Open Gov platform, the Open Gov tags should be the ones that appear (not the OPSI tags). The opposite would be true when looking at the OPSI page (https://oecd-opsi.org/case_type/opsi/).

**Comment by jlberryhill** [comment]
Forgot screenshot.

![tagsissue](https://user-images.githubusercontent.com/7728105/48123513-68fb7e80-e27a-11e8-850f-0e057d0991c2.PNG)

**Comment by conlaccento** [comment]
Everything fixed here
